### ISSUE TITLE
No accounting for objects as Map keys 

### ISSUE THREAD

**Issue by rwaldron** [alex-weej/es-extensible-collection-literal#2]
Using an object as a key in a Map is common—it's certainly one of the most valuable use cases of a `Map`, but this proposal mentions nothing about that. 

So does this: 

```js
const key = {};
const map = new Map([ [key, 1] ]);
```

Mean the same as: 

```js
const key = {};
const map = Map#{
  key: 1
};
```

**Comment by alexweej** [comment]
That is correct.

**Comment by alexweej** [comment]
@rwaldron for the benefit of other readers, can you think of an improvement to the wording that might make this more obvious without being too much of a distraction?

Thanks
